[workspace]
authors = ["Logan Lang <lllangWV@gmail.com>"]
channels = ["conda-forge"]
name = "ccmarket"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pyyaml = ">=6.0.3,<7"
